services:
  - type: web
    name: wormhole-tracker-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    rootDir: .
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: VCPKG_ROOT
        value: /opt/vcpkg
      - key: PORT
        value: 9001
      - key: NODE_ENV
        value: production

  - type: web
    name: wormhole-tracker-frontend
    env: static
    buildCommand: cd frontend && npm install && WS_URL=wss://wormhole-tracker-backend.onrender.com npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true 